# SPDX-FileCopyrightText: 2023 Graz University of Technology.
# SPDX-License-Identifier: MIT

name: i18n:pull translations
on: workflow_dispatch # manually trigger

jobs:
  i18n-pull:
    uses: inveniosoftware/invenio-i18n/.github/workflows/i18n-pull-bas.yml@master
    secrets: inherit
